### ISSUE TITLE
Searches are timing out

### ISSUE THREAD

**Issue by bergerx** [peduarte/magno#10]
Hi, i've been quite happy using this service for a while. But recently the searched are returning a white page. I briefly checked the JS console and saw that the api endpoint returning a timeout like this:

```
{"errorMessage":"2019-10-17T09:53:15.574Z ff808d2a-abdb-47d3-b35e-b919412f48df Task timed out after 10.01 seconds"}
```

![image](https://user-images.githubusercontent.com/45531/66998701-9d9fc900-f0cc-11e9-8454-459264187a30.png)

**Comment by peduarte** [comment]
oops sorry just seen this, should be fixed since this is such an old issue. my bad
