### ISSUE TITLE
Magno no longer working

### ISSUE THREAD

**Issue by iclems** [peduarte/magno#13]
It's currently failing with error: 

error_type: "SEARCH_ERROR"
error_message: "Request failed with status code 502"

How can I help?

**Comment by peduarte** [comment]
Hmmm, thanks for that, I'll look into it. Cheers!

**Comment by peduarte** [comment]
I just tested it and it's working for me, can you retry?

**Comment by iclems** [comment]
It’s working again. It had been failing for me for several days both from my mobile and laptop

Clément

Sent via Superhuman iOS ( https://sprh.mn/?vip=cwehrung@gmail.com )

**Comment by peduarte** [comment]
thats not good! sorry about that. please let me know if it happens again so I can investigate. thanks!
