### ISSUE TITLE
Invalid Redirect URI

### ISSUE THREAD

**Issue by tylervick** [peduarte/magno#14]
Hello,

I'm receiving an error when attempting to step through the Put.io auth flow for Magno.

When hitting Confirm on the Put.io auth prompt, I'm redirected to this Put.io error screen.
```
{
error_id: null,
error_message: "Invalid redirect_uri",
error_type: "INVALID_REDIRECT_URI",
error_uri: "http://api.put.io/v2/docs",
extra: { },
status: "ERROR",
status_code: 400
}
```

**Comment by peduarte** [comment]
Thanks for that. Netlify updated their URL from .com to .app so I’ll update this today. 

Cheers!

**Comment by tylervick** [comment]
Of course! I was very excited to use your service, the UI alone looks beautiful. Glad to see this getting fixed 😄

**Comment by peduarte** [comment]
I've updated the URL now, can you check that it's all good for you?
